name       : python-trustme
version    : 0.9.0
release    : 4
source     :
    - https://github.com/python-trio/trustme/archive/refs/tags/v0.9.0.tar.gz : e9f2544bcc39583a62b5d39d9f0ce3da8528ee448911035a679f7ddb1edeab5e
license    : Apache-2.0
component  : programming.python
summary    : Quality TLS certs while you wait, for the discerning tester
description: |
    Quality TLS certs while you wait, for the discerning tester
builddeps  :
    - python-cryptography
    - python-idna
    - python-pytest
    - python-openssl # check
    - python-service-identity # check
rundeps    :
    - python-cryptography
    - python-idna
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
